In [1]:
from pathlib import Path
from sqlalchemy import create_engine
import pandas as pd

root = Path.cwd().parent
path = root / "_docs" / "dulcineadb" / "proyectobot.db"

engine = create_engine(f"sqlite:///{path}")

In [7]:
QUERY = """
select 
    channel_name,
    channel_id,
    author_name,
    created_at

from discord_messages
where 
    guild_id = 772855809406271508 and
    LOWER(channel_name) LIKE 'o%'
order by created_at;
"""

df = pd.read_sql(QUERY, engine)
df

,channel_name,channel_id,author_name,created_at
0,origination,1327290419129749566,Mafe Cruz,2026-01-26T22:12:59.234000+00:00
1,origination,1327290419129749566,Natalia Avendaño Rúa,2026-01-26T22:37:08.399000+00:00
2,origination,1327290419129749566,Silvia María,2026-01-26T23:00:50.345000+00:00
3,origination,1327290419129749566,Sofia Bolaños,2026-01-26T23:09:17.349000+00:00
4,origination,1327290419129749566,Ana Carolina Zapata,2026-01-26T23:14:33.902000+00:00
...,...,...,...,...
85,origination,1327290419129749566,Ana Carolina Zapata,2026-02-23T22:24:21.220000+00:00
86,origination,1327290419129749566,Natalia Avendaño Rúa,2026-02-23T22:42:37.860000+00:00
87,origination,1327290419129749566,Sofia Bolaños,2026-02-24T12:35:53.039000+00:00
88,origination,1327290419129749566,Sofia Bolaños,2026-02-24T12:46:07.607000+00:00
89,origination,1327290419129749566,Natalia Avendaño Rúa,2026-02-26T23:17:49.312000+00:00

In [8]:
QUERY = """
select 
    channel_name,
    channel_id,
    author_name,
    created_at

from discord_messages
where 
    guild_id = 772855809406271508 and
    LOWER(channel_name) LIKE 'v%'
order by created_at;
"""

df = pd.read_sql(QUERY, engine)
df

,channel_name,channel_id,author_name,created_at
0,validation,1321563772271464538,Sofia Bolaños,2026-01-24T19:16:54.538000+00:00
1,validation,1321563772271464538,María José Borja Fierro,2026-01-24T19:56:56.484000+00:00
2,validation,1321563772271464538,María José Borja Fierro,2026-01-24T19:56:57.681000+00:00
3,validation,1321563772271464538,Sofia Bolaños,2026-01-26T13:32:45.652000+00:00
4,validation,1321563772271464538,María José Borja Fierro,2026-01-26T13:39:59.684000+00:00
...,...,...,...,...
439,validation,1321563772271464538,Sofia Bolaños,2026-02-26T13:53:13.806000+00:00
440,validation,1321563772271464538,Felipe Ramirez Franco,2026-02-26T16:11:33.683000+00:00
441,validation,1321563772271464538,Sofia Bolaños,2026-02-26T17:01:19.671000+00:00
442,validation,1321563772271464538,Sofia Bolaños,2026-02-26T17:01:36.381000+00:00
443,validation,1321563772271464538,Sofía Ruiz,2026-02-27T11:53:44.011000+00:00