In [3]:
from pathlib import Path
from sqlalchemy import create_engine

root = Path.cwd().parent
path = root / "_docs" / "dulcineadb" / "proyectobot.db"

engine = create_engine(f"sqlite:///{path}")
print(path)

# probar conexión
with engine.connect() as conn:
    print("Conexión exitosa")
    print("\n"*5)

/home/somath/Documents/dev/edubot/_docs/dulcineadb/proyectobot.db
Conexión exitosa

In [4]:
from sqlalchemy import inspect

inspector = inspect(engine)

tables = inspector.get_table_names()
print("Tablas:", tables)
print("\n"*5)



for table in tables:
    print(f"\nTabla: {table}")
    columns = inspector.get_columns(table)

    for col in columns:
        print(f"  {col['name']} - {col['type']}")

print("\n"*5)

Tablas: ['conversation_segments', 'discord_messages', 'project_status_cache', 'projects', 'segment_messages']







Tabla: conversation_segments
  id - INTEGER
  project_id - INTEGER
  channel_id - TEXT
  channel_name - TEXT
  content_summary - TEXT
  entry_type - TEXT
  importance - INTEGER
  action_items - TEXT
  key_message_url - TEXT
  participants - TEXT
  created_at - TIMESTAMP

Tabla: discord_messages
  id - INTEGER
  discord_msg_id - TEXT
  guild_id - TEXT
  channel_id - TEXT
  channel_name - TEXT
  author_id - TEXT
  author_name - TEXT
  content - TEXT
  reply_to_msg_id - TEXT
  message_url - TEXT
  created_at - TIMESTAMP
  processed - INTEGER

Tabla: project_status_cache
  id - INTEGER
  project_id - INTEGER
  summary - TEXT
  updated_at - TIMESTAMP

Tabla: projects
  id - INTEGER
  code - TEXT
  display_name - TEXT
  aliases - TEXT
  status - TEXT
  created_at - TIMESTAMP

Tabla: segment_messages
  segment_id - INTEGER
  discord_msg_id - TEXT

In [7]:
import pandas as pd

In [8]:
df = pd.read_sql("SELECT * from conversation_segments", engine)
df.head()

,id,project_id,channel_id,channel_name,content_summary,entry_type,importance,action_items,key_message_url,participants,created_at
0,1,1,1414989101882413197,solenium/0085 - Curumani Occidente (COLCEST232P1),Ivan confirma que se envía un documento hoy.,update,3,[],https://discord.com/channels/13088857066214523...,"[""Ivan Bernal"", ""Eduardo Ospina""]",2026-02-17 13:04:28
1,2,1,1414989101882413197,solenium/0085 - Curumani Occidente (COLCEST232P1),Simón pregunta si tienen permiso de conexión d...,info,7,[],https://discord.com/channels/13088857066214523...,"[""Sim\u00f3n Gonz\u00e1lez"", ""Eduardo Ospina""]",2026-02-17 13:04:28
2,3,1,1414989101882413197,solenium/0085 - Curumani Occidente (COLCEST232P1),Sofia informa que aún no tienen el acuerdo fir...,info,5,[],https://discord.com/channels/13088857066214523...,"[""Sofia Bola\u00f1os""]",2026-02-17 13:04:28
3,4,1,1414989101882413197,solenium/0085 - Curumani Occidente (COLCEST232P1),Eduardo pregunta por el avance de la construcc...,update,8,[],https://discord.com/channels/13088857066214523...,"[""Eduardo Ospina"", ""Ivan Bernal""]",2026-02-17 13:04:28
4,5,1,1414989101882413197,solenium/0085 - Curumani Occidente (COLCEST232P1),Jaibet solicita el cronograma en otro formato ...,update,8,[],https://discord.com/channels/13088857066214523...,"[""Jaibet Paola"", ""Ivan Bernal"", ""Bryam Duque"",...",2026-02-17 13:04:28

In [9]:
df = pd.read_sql("SELECT * from discord_messages", engine)
df.head()

,id,discord_msg_id,guild_id,channel_id,channel_name,author_id,author_name,content,reply_to_msg_id,message_url,created_at,processed
0,1,1470773962098212973,772855809406271508,772855809406271511,general,1218192176547102831,ADRIANA JARABA,"Buenas buenas, espero que estén muy bien.\n\nA...",None,https://discord.com/channels/77285580940627150...,2026-02-10T13:30:38.223000+00:00,1
1,2,1470845063541166333,772855809406271508,772855809406271511,general,472510585624330261,Juan José Pacheco Arias,https://klipy.com/gifs/welcome-1339,1470773962098212973,https://discord.com/channels/77285580940627150...,2026-02-10T18:13:10.128000+00:00,1
2,3,1471510639200571597,772855809406271508,772855809406271511,general,1366405444591026227,Paola Ortiz Bayona,Holisssss @here\n\nAlguien sabe de quién es es...,None,https://discord.com/channels/77285580940627150...,2026-02-12T14:17:55.731000+00:00,1
3,4,1471510905622757562,772855809406271508,772855809406271511,general,1337397066938318940,Mateo Vargas Medina,"Hola, es Miguel Beltrán",None,https://discord.com/channels/77285580940627150...,2026-02-12T14:18:59.251000+00:00,1
4,5,1471510930868142321,772855809406271508,772855809406271511,general,1337397066938318940,Mateo Vargas Medina,es usuario de que? jaja,None,https://discord.com/channels/77285580940627150...,2026-02-12T14:19:05.270000+00:00,1

In [10]:
df = pd.read_sql("SELECT * from project_status_cache", engine)
df.head()

,id,project_id,summary,updated_at
0,28,217,RESUMEN:\nSe ha suspendido el proceso en un te...,2026-02-23T19:20:47.813575+00:00
1,32,64,RESUMEN:\nSe preguntó sobre el estado del proy...,2026-02-24T15:30:32.023275+00:00
2,36,67,RESUMEN:\nSe han discutido varios aspectos del...,2026-02-24T16:45:42.187593+00:00
3,37,46,RESUMEN:\nEl proyecto COLCEST14P1 (Agustín Cod...,2026-02-24T16:47:45.077705+00:00
4,38,161,RESUMEN:\nEl proyecto COLCEST454P1 (San Diego ...,2026-02-25T16:45:57.522572+00:00

In [11]:
df = pd.read_sql("SELECT * from projects", engine)
df.head()

,id,code,display_name,aliases,status,created_at
0,1,COLCEST232P1,COLCEST232P1,"[""colcest232p1""]",active,2026-02-17 13:04:28
1,2,COLSANT53P1,COLSANT53P1,"[""colsant53p1""]",active,2026-02-17 13:05:23
2,3,COLCEST14P1_AGUSTIN-CODAZZI_SUR,COLCEST14P1_AGUSTIN-CODAZZI_SUR,"[""colcest14p1_agustin-codazzi_sur""]",active,2026-02-17 13:05:44
3,4,COLSANT188P2_OIBA_OCCIDENTE,COLSANT188P2_OIBA_OCCIDENTE,"[""colsant188p2_oiba_occidente""]",active,2026-02-17 13:05:44
4,5,COLCEST6,COLCEST6,"[""colcest6""]",active,2026-02-17 13:05:53

In [12]:
df = pd.read_sql("SELECT * from segment_messages", engine)
df.head()

   segment_id       discord_msg_id
0           1  1470766969505447967
1           2  1470800025138237481
2           2  1470805649616011476
3           3  1470807526332305572
4           4  1471634758852153405

.

.

.

.

.

.

.

.

In [13]:
df = pd.read_sql("SELECT * from discord_messages", engine)
df.shape

(10266, 12)

In [14]:
QUERY = """
SELECT
    channel_id,
    COUNT(id) as message_count
FROM discord_messages
GROUP BY channel_id
ORDER BY message_count DESC;
"""

df = pd.read_sql(QUERY, engine)
df

              channel_id  message_count
0    1441518428333543506           1148
1    1399093133056278549            585
2    1346863207259701338            452
3    1321563772271464538            439
4    1316032431769522226            396
..                   ...            ...
160  1472998533064818972              1
161  1472998711989764150              1
162  1473044039946338525              1
163  1473795297791443016              1
164  1476602279023870072              1

[165 rows x 2 columns]

In [15]:
estadisticas = df['message_count'].describe()

In [16]:
estadisticas

count     165.000000
mean       62.218182
std       125.742675
min         1.000000
25%         3.000000
50%        15.000000
75%        66.000000
max      1148.000000
Name: message_count, dtype: float64

In [17]:
QUERY = """
SELECT
    channel_id,
    COUNT(id) as message_count
FROM discord_messages
GROUP BY channel_id
ORDER BY message_count DESC
LIMIT 10;
"""

df = pd.read_sql(QUERY, engine)
df

            channel_id  message_count
0  1441518428333543506           1148
1  1399093133056278549            585
2  1346863207259701338            452
3  1321563772271464538            439
4  1316032431769522226            396
5  1357437165738393822            342
6  1320470324441256036            325
7  1366535659178950817            307
8  1361420368346091703            260
9  1387205788157612062            260

In [18]:
QUERY = """
SELECT
    id,
    channel_name,
    author_name,
    content,
    reply_to_msg_id,
    created_at
FROM discord_messages
WHERE channel_id = '1441518428333543506'
ORDER BY created_at DESC
LIMIT 30;
"""

df = pd.read_sql(QUERY, engine)
df

,id,channel_name,author_name,content,reply_to_msg_id,created_at
0,353444,solenium-originacion/Novedades visitas,Ale Perdomo,"His, quedo para el Jueves 5",1477049606197084355,2026-02-27T22:40:27.693000+00:00
1,330891,Novedades visitas,Mafe Cruz,"Ya confirmo con Ana, qué día hacen topo?",1477049494247047178,2026-02-27T21:07:48.372000+00:00
2,330890,Novedades visitas,Ale Perdomo,"Hellous, lo podemos hacer el mismo dia de la T...",1477041697157415013,2026-02-27T21:07:21.681000+00:00
3,330868,Novedades visitas,Mafe Cruz,<@1329442596056993822> Alguien estará por Piji...,None,2026-02-27T20:36:22.710000+00:00
4,314425,Novedades visitas,Ale Perdomo,De unis!,1477021208791875635,2026-02-27T19:32:40.490000+00:00
5,314402,Novedades visitas,María José Borja Fierro,"Ale esta incompleta, ya corrobore con el equip...",1477015395817754766,2026-02-27T19:14:57.903000+00:00
6,314372,Novedades visitas,Ale Perdomo,"Holisss, Juanes me dijo que ya no, que ya esta...",1477009914508476428,2026-02-27T18:51:51.982000+00:00
7,314360,Novedades visitas,Sofia Bolaños,"Nada, que aún no tienen información de eso",1477004206799065172,2026-02-27T18:44:04.940000+00:00
8,314354,Novedades visitas,María José Borja Fierro,en lo posible si lo podemos dejar iniciando se...,None,2026-02-27T18:30:15.749000+00:00
9,314353,Novedades visitas,María José Borja Fierro,<@1329442596056993822> Ale podemos volver a CO...,None,2026-02-27T18:30:05.136000+00:00
10,306188,Novedades visitas,María José Borja Fierro,y se sabe aprox cuando?,1476986200748195920,2026-02-27T18:07:24.312000+00:00
11,298026,Novedades visitas,Sofia Bolaños,Pues en general,None,2026-02-27T16:56:03.964000+00:00
12,298025,Novedades visitas,Sofia Bolaños,"Nopi, ya llamamos al contacto que tenemos en l...",1476982557575876628,2026-02-27T16:55:51.335000+00:00
13,295993,Novedades visitas,María José Borja Fierro,vale la pena ir a la alcaldia?,1476966334565974067,2026-02-27T16:41:22.735000+00:00
14,277814,Novedades visitas,María José Borja Fierro,Licencias de construcción - Diego y Nicol,1476969893441048708,2026-02-27T15:52:01.221000+00:00
15,277810,Novedades visitas,Mafe Cruz,Radicado de solicitud de restricciones ambient...,1476969978111594588,2026-02-27T15:52:00.059000+00:00
16,276879,Novedades visitas,Ale Perdomo,"Holis, que tipo de radicado?",1476966143464968213,2026-02-27T15:51:23.557000+00:00
17,276232,Novedades visitas,Ale Perdomo,"Holis, sep. Por fa me dejan la actividad que s...",1476965105437507755,2026-02-27T15:51:03.370000+00:00
18,260320,Novedades visitas,Sofia Bolaños,Y de Gamarra la alcadía no ha sacado recibos a...,1476965105437507755,2026-02-27T15:36:54.868000+00:00
19,271221,solenium-originacion/Novedades visitas,Sofia Bolaños,"Tamalameque todavia no tenemos el recibo, que ...",None,2026-02-27T15:36:09.678000+00:00
20,271219,solenium-originacion/Novedades visitas,Mafe Cruz,"Hola, <@1329442596056993822> Podemos ir a corp...",None,2026-02-27T15:36:09.306000+00:00
21,271217,solenium-originacion/Novedades visitas,María José Borja Fierro,Ale la otra semana podemos ir por favor a Gala...,None,2026-02-27T15:32:01.821000+00:00
22,248814,solenium-originacion/Novedades visitas,María José Borja Fierro,ceibas cox,None,2026-02-27T14:50:28.028000+00:00
23,244768,Novedades visitas,Sofia Bolaños,"Holiss, de que terreno ?",None,2026-02-27T14:48:56.251000+00:00
24,241025,Novedades visitas,María José Borja Fierro,<@1143552043164909690> sabes?,1476714270640312441,2026-02-26T22:55:44.659000+00:00
25,241024,Novedades visitas,Ale Perdomo,Tengo entendido que los postes que Faltan son ...,1476711060261048373,2026-02-26T22:55:18.145000+00:00
26,241014,Novedades visitas,María José Borja Fierro,como podemos ayudarles a EPC con eso?,None,2026-02-26T22:42:32.731000+00:00
27,241012,Novedades visitas,Alan Martínez,El dron de Miguel lo tiene michel,1476706478642692107,2026-02-26T22:34:25.931000+00:00
28,241011,Novedades visitas,Alan Martínez,El otro se enviara a Derwin,None,2026-02-26T22:33:58.233000+00:00
29,241010,Novedades visitas,Alan Martínez,Estuvo en reparación en medellin y se enviará ...,1476708416264339630,2026-02-26T22:33:53.686000+00:00

Tabla: discord_messages
  id - INTEGER
  discord_msg_id - TEXT
  guild_id - TEXT
  channel_id - TEXT
  channel_name - TEXT
  author_id - TEXT
  author_name - TEXT
  content - TEXT
  reply_to_msg_id - TEXT
  message_url - TEXT
  created_at - TIMESTAMP
  processed - INTEGER